#%RAML 1.0

title: Mulesoft Salesforce Integration Components API
description: REST API connects Mulesoft environment to the Salesforce through their Mulesoft components available 

/user-info:
  get: