#%RAML 1.0

title: Mulesoft Salesforce Integration REST API
description: REST API connects Mulesoft environment to the Salesforce through their REST APIs available

/token:
  /rest:
    get:
  /soap:
    get:
/account:
  post:
    body:
      application/json:
        